### ISSUE TITLE
Able to add more than 1 value to each input

### ISSUE THREAD

**Issue by waseemh-io** [drac94/react-auth-code-input#33]
https://github.com/drac94/react-auth-code-input/blob/5ebdf88181aa19ca42c5f53eaab1a136ca251a70/src/index.tsx#L85-L104

Even though each input has `maxLength={1}`, I am able to still type in more than 1 value for each input.
This happens:
1. After you complete all the inputs and continuously try to add more values. The values get appended to the last input.
2. If you input a value then click and go back to an input and attempt to add other values.

<img width="817" alt="Screen Shot 2022-02-13 at 12 10 42 PM" src="https://user-images.githubusercontent.com/16570741/153766305-c51921cd-afed-4da9-922b-aa1e06d86561.png">

**Comment by drac94** [comment]
Hi @waseemh-io thanks for creating the issue. I was reviewing it and found that when using `type='number'` in an input the `maxLength` property is ignored. To solve it I had to do the checks using JS and setting the `min` and `max` properties. By doing this I also saw some other inconsistencies caused because the `allowedCharacters` property accepted a Regex. For version 3 I decided to limit this to only 3 modes: alphanumeric, alpha, and numeric. I also added a bunch of tests to make the component more trustable. This version is already live if you want to check it. Thanks.
